const nom = document.getElementById('nom')
nom.style.marginLeft = ('800px')
const titre = document.getElementById('titre')
titre.style.marginLeft = ('830px')
const nav = document.getElementById('nav')
nav.style.marginLeft = ('570px')
